### ISSUE TITLE
The functionality does not work

### ISSUE THREAD

**Issue by Artem2710** [Offerel/roundcube_primitivenotes#12]
Hello. The functionality of creating new notes does not work. I tried to manually add the file and it was displayed, but the editing and deletion functionality also does not work. Also logging does not work. Tell me what could be the problem?
If the notes are stored in a separate directory, will they be deleted when the user is deleted? Or is it better to store these notes in the same directory where the mail is stored?
Is it possible to limit the size of storage for notes? Thank.

**Comment by Offerel** [comment]
Without more detailed information I cannot answer your questions. How did you configure the plugin? Which paths did you specify in the config? Are the permissions set correctly? The web server must have read and write permissions on the path you specified.

What do you mean by saving the notes in the same folder as the notes? Email usually comes from the local or remote IMAP server, but the notes are stored in a locally accessible filesystem.

If you want to set a limit for notes, this can only work at the file system level. Depending on which filesystem you are using, it may also support quota limits. This is not a functionality of the plugin.

**Comment by Artem2710** [comment]
![2019-02-08_1036](https://user-images.githubusercontent.com/38757512/52467334-d5459100-2b8d-11e9-8eef-5a55a1787cf3.png)
My configuration settings in the attachment. Folder resolution is 777.
Does the plugin create a new directory for each new user? Or should the admin do these settings manually?

**Comment by Offerel** [comment]
If the path /tmp/hdd/<username>/files/Notes/ does not exist, it will be created at first plugin call with permission 0774. If it is existing and accessible for the Webserver, it is using the given state. If the directory is not existing and cant be created, a error is logged to Roundcube error-log.

BTW: I cant recommend to use /tmp or its sub folders as storage. In most cases /tmp is only used and controlled by the operating system to store temporary data.

**Comment by Artem2710** [comment]
Thanks for the answer, it works.
