### ISSUE TITLE
uploading images

### ISSUE THREAD

**Issue by Artem2710** [Offerel/roundcube_primitivenotes#13]
Hello. My question is not related to your plugin. I need to make the functionality of uploading images to a specific directory on the server. Please tell me how can I add this functionality to the existing plugins? Or create your own plugin? Is there any manual for creating plugins for roundcube? Thank.

**Comment by Offerel** [comment]
I didn't know your concrete idea, but maybe for images, you can use my gallery plugin at https://github.com/Offerel/roundcube_pictures. 

To develop your own plugin, you can use in principle the usual PHP functions. As a starting point you can go to https://github.com/roundcube/roundcubemail/wiki/Plugin-API to develop your own plugins.

**Comment by Artem2710** [comment]
Thank you very much for your answer.

**Comment by Artem2710** [comment]
Sorry for interrupting. I need the functionality of downloading images from the local environment to the server. It only has to be two inputs with the file and button types. Can you help me with this?

**Comment by Offerel** [comment]
In principle this should not be a problem but there is more to be considered. How and where do you want to call the functionality? Should the function only be available in one dedicated task or in all tasks or should one task be excluded? Should the target directory be configurable for the upload? What permissions should the file have in the target directory?  Is the target directory individual for each user or is everything uploaded to one directory? Furthermore, I recommend to check if the files are really valid and that you don't catch any malicious code that might compromise the Roundcube installation or possibly read data.

I would do the actual interface (if it is really only about uploading single images) with a CSS popup/layer. Speaking a simple HTML fragment, which only appears when I call the upload function and disappears automatically when the upload is finished with the whole process. At least in modern browsers this works also with Drag&Drop and multiple files at once. But these are more or less just small modifications.

In the current Primitivenotes plugin, there is a similar function. Take a look at the plugin toolbar. The last button in that bar is a upload function. Maybe you can use that as a starting point. The is no additional HTML popup, it calls directly the local file picker and upload the file immediately after confirmation of the file picker itself. Feel free to use that functions in your plugin.

**Comment by Artem2710** [comment]
The target directory should be one for all, the file size should not exceed 50 kb, the png file format. When you click on the Company Logo in the menu section on the right there should be a button and a description of the file.
![2019-02-15_1533](https://user-images.githubusercontent.com/38757512/52860656-b9675f80-3138-11e9-9adb-413dfd00f1bb.png)
![2019-02-15_1538](https://user-images.githubusercontent.com/38757512/52860657-b9675f80-3138-11e9-8ea5-7b965967bdd3.png)

**Comment by Offerel** [comment]
Yeah, you can do that. It would work. But I wouldn't recommend it. If you use one directory for all users, one user can overwrite the logo of the other users. I guess you want to use the "Company Logo" as the logo for Roundcube itself. In this case I would not allow each user to upload the logo separately. All settings made via this settings page should only be relevant for each individual user and not globally for the entire installation. I would not make global configurations accessible for individual users. These are rather things that you as the admin define in the config files.

**Comment by Artem2710** [comment]
Can you tell what part of the code in the primitivenotes plugin is responsible for forming the upload button, sending the file upload form? I would be very grateful if you provide me with a ready-made solution for my task.

**Comment by Offerel** [comment]
Sorry, but I didn't have the time to write plugins for others. But I'm sure you find examples how you can upload files and do what ever you want want with them. If you didn't find the right code pieces in my sources, a simple Google search offer thousands of php upload examples.
