### ISSUE TITLE
errors in the error log

### ISSUE THREAD

**Issue by Artem2710** [Offerel/roundcube_primitivenotes#14]
The plugin works, but there are such errors in the error log:

*27642 FastCGI sent in stderr: "PHP message: PHP Warning:  usort() expects parameter 1 to be array, null given in /var/www/roundcubemail-1.3.8/plugins/primitivenotes/notes.php on line 349

PHP Warning:  Invalid argument supplied for foreach() in /var/www/roundcubemail-1.3.8/plugins/primitivenotes/notes.php on line 649" while reading response header from upstream

PHP Warning:  filesize(): stat failed for /srv/mail-storage-01/notes/noreply@maillinker.com/owns/files/ in /var/www/roundcubemail-1.3.8/plugins/primitivenotes/primitivenotes.php on line 85" while reading response header from upstream

*24024 FastCGI sent in stderr: "PHP message: PrimitiveNotes: Note not found. Attach the note to the mail failed.

These errors appear even if you do not use the notes plugin.

**Comment by Offerel** [comment]
Are you sure, that you are using the actual version of this plugin? There is no usort() function on line 349...

**Comment by Artem2710** [comment]
Updated the version of the plugin to the last. Now gives this error:

[error] 1065#0: *40317 FastCGI sent in stderr: "PHP message: PHP Warning:  usort() expects parameter 1 to be array, null given in /var/www/roundcubemail-1.3.8/plugins/primitivenotes/notes.php on line 376
PHP message: PHP Warning:  Invalid argument supplied for foreach() in /var/www/roundcubemail-1.3.8/plugins/primitivenotes/notes.php on line 675" while reading response header from upstream

**Comment by Artem2710** [comment]
Another such mistake:

[error] 1065#0: *40415 FastCGI sent in stderr: "PHP message: PHP Warning:  strpos(): Offset not contained in string in /var/www/roundcubemail-1.3.8/plugins/primitivenotes/notes.php on line 463" while reading response header from upstream

40294 FastCGI sent in stderr: "PHP message: PHP Warning:  rename(/srv/mail-storage-01/notes/artem.stanislavenko@sky-tech.co/owns/files/,/srv/mail-storage-01/notes/artem.stanislavenko@sky-tech.co/owns/files/РєР°Р°Рє.html): Invalid argument in /var/www/roundcubemail-1.3.8/plugins/primitivenotes/notes.php on line 297" while reading response header from upstream

**Comment by Offerel** [comment]
This seems to indicate, as mentioned before, that there are no notes on the configured directory. Or that the permission is not sufficient for the web server to write to the configured directory.

Please check if the permission is sufficient and the configured path is correct. Try to avoid system directories. Check whether the web server may have write access to mountpoints (if there are some involved).

**Comment by Artem2710** [comment]
Access to the catalog 777. Is it possible to remove the error in case there are no notes? This clogs the log

**Comment by Offerel** [comment]
Since these come as system messages from the kernel, I can't do anything with the plugin itself. Here you can only configure the system correctly or prevent log entries of this kind system-wide. However, this would also suppress other messages. I would seriously advise against this. The only reasonable way is to configure the plugin so that the path points to a correct directory. Anything else makes no real sense.
