### ISSUE TITLE
Save button for notes with plain text.

### ISSUE THREAD

**Issue by allexnew** [Offerel/roundcube_primitivenotes#17]
It is not clear how to save a note with plain text. There is no save button for it. For HTML and MD notes there is a save button.

**Comment by allexnew** [comment]
Found out that you can save notes with plain text if you press Enter when the cursor is in the title bar.
However, you can guess this only by accident.

**Comment by Offerel** [comment]
Zhanks for reporting. That will be fixed with the next release.
