### ISSUE TITLE
The conflict between the Notes and plugin automatic_addressbook

### ISSUE THREAD

**Issue by allexnew** [Offerel/roundcube_primitivenotes#18]
The notes may conflict with the plugin [automatic_addressbook](https://github.com/sblaisot/automatic_addressbook/blob/master/INSTALL).  I can include either notes or automatic_addressbook. 

`[05-Apr-2019 12:01:44 Europe/Moscow] PHP Warning:  usort() expects parameter 1 to be array, null given in /var/www/roundcube/plugins/primitivenotes/notes.php on line 376
[05-Apr-2019 12:01:44 Europe/Moscow] PHP Warning:  Invalid argument supplied for foreach() in /var/www/roundcube/plugins/primitivenotes/notes.php on line 675
`

**Comment by Offerel** [comment]
I am relatively sure that this has nothing to do with any other plugin. There are 3 possible reasons. Either there are no notes in the configured directory for the notes or the path is configured wrong or the permission is not correct. I have now added a check that inserts a note in the logfile.
