### ISSUE TITLE
Multiple note send

### ISSUE THREAD

**Issue by dktcoding** [Offerel/roundcube_primitivenotes#19]
Hi, I have a question, would it be possible to send multiple notes?

Use case: Currently I use one note with multiple links to files in other server, and once a month I have to send the note and the files. Since primitive notes is able to upload files I was wondering if it was possible to select multiple "notes" (or one note and a lot of files) and send them in one email.

For instance in the screenshot:
![Screen Shot 2019-04-15 at 16 58 04](https://user-images.githubusercontent.com/709639/56161348-a8539700-5f9f-11e9-81b1-ce8ef7e0ed35.png)

I can filter all tagged elements that should be sent in only one email.

Regards

**Comment by Offerel** [comment]
No, that snot possible and not a planned feature.
