### ISSUE TITLE
Notes are not saved

### ISSUE THREAD

**Issue by krater** [Offerel/roundcube_primitivenotes#2]
Hello,

I installed the current version in git. Edited the config file as this:
<?php
// absolute base! path where your notes are stored
$config['notes_basepath'] = '/var/spool/notes/';

// notes folder under basepath. in the end the folder is calculated by 'basepath' + 'username' + 'notes_folder'
$config['notes_folder'] = '/files/Notes/';
?>

Owner of this folder is www-data.

After creating a note in the editor and save, I have 
/var/spool/notes/<my username>/files/Notes
but the folder is empty. 
Additionally I have no notes in the list. 

I don't have a error-message in the apache-log, in firefox-log I have "TypeError: markdown is undefined, notes.php line 79"

Same tested with chrome.

Do you have any idea ?

**Comment by Offerel** [comment]
Do you used the 'master' branch or the new ['ajax_test' branch](../tree/ajax_test)? In the master branch, there is a problem with the markdown editor. This should be fixed in 'ajax_test' branch. I will merge this to the current master, currently im waiting for response if #1 is solved with this. 

If you try this branch, can you please test it with larry and also classic skin and report back to me?

I don't know, if using /var/spool/notes is a good idea, since /var/spool has special meaning in a Linux System. Anyway, it should work at least temporary. Are there additional error in the Roundcube Logfile? Can you please show me your config from your config.inc.php for this plugin?

**Comment by krater** [comment]
Here is the missing config from the plugin, github removed it because the php-tags:
// absolute base! path where your notes are stored
$config['notes_basepath'] = '/var/spool/notes/';

// notes folder under basepath. in the end the folder is calculated by 'basepath' + 'username' + 'notes_folder'
$config['notes_folder'] = '/files/Notes/';

The // should be a /[my-username]/ but this removed github too.

I used the master-branch, and I don't have layout-issues with larry at the moment with Palemoon 27.7.1 (64-bit) and with chromium(can't look at the version currently, but I think its a really old one).

In the error-log I have the line:
PHP Fatal error:  Call to undefined function array_column() in /private-backup/badterrorist.com/webmehl/round/plugins/primitivenotes/notes.php on line 259

But only when I load the plugin, when I press the save-button I don't have any additional error.

I will no try the other branch in the next hours.

**Comment by krater** [comment]
I WILL try the other branch in the next hours.

**Comment by Offerel** [comment]
Many thx. Meanwhile i have added some things in the wiki. Maybe there are tips for you, how the thigs do work.

**Comment by sai-mike** [comment]
With v1.0.0, I have no issues creating or editing HTML notes.  However, when I try to edit the title of an uploaded jpeg or pdf the change is not saved.

Select an existing upload, click Edit button, change the upload's title, click the save button - new title is not saved.
I don't see any errors in the Roundcube or Apache logs related to this.

**Comment by Offerel** [comment]
I have found and fixed and issue with saving binary files like jpg, png and pdf. this should solve your problem.

**Comment by krater** [comment]
Sorry for my late answer, but many thanks for the help. Now with the current master branch it works :)
Additionally I moved the notes to another place.
