### ISSUE TITLE
plugin

### ISSUE THREAD

**Issue by alfredo-ardito** [Offerel/roundcube_primitivenotes#21]
I get this error after upgrading
Failed to load plugin url: https://domain.xxx/webmail/program/js/tinymce/langs/en_US.js

**Comment by Offerel** [comment]
Could you please give me more information's? What have you upgraded? Roundcube or the plugin or something on your server? And what do you mean with plugin url? It seems, that the above path is not the url to the plugin.

**Comment by alfredo-ardito** [comment]
I upgraded both. Roundcube ver is 1.3.9 and primitivenotes is 1.4.2
When I try to create a new note it displays this message on the top.
"Failed to load plugin url: https://domain.xxx/webmail/program/js/tinymce/langs/en_US.js"
What I can do is remove the plugin and directories concerning primitvenotes and then try 
to reinstall it again. 
Any clue?

**Comment by Offerel** [comment]
I think, i have a temporary fix: please change in notes.php line 474 from `if($language != 'en_US')` to `//if($language != 'en_US')`.

I think there was a change in tinymce changing language detection, which is not currently respected in my code. I change that in the next version.

**Comment by alfredo-ardito** [comment]
Great. issue fixed. thx

**Comment by Offerel** [comment]
fixed with 1f94add0746281896f3b2153213fd5182fb3c8f8
