### ISSUE TITLE
Attaching notes to email

### ISSUE THREAD

**Issue by abcug** [Offerel/roundcube_primitivenotes#25]
It would be very useful if we could attach the note to an email and see its attached status in the mail view and / or mail list ( and we could jump in from there ).
----
...attaching the Hungarian language file ( 'hu_HU.inc' - UTF-8 with BOM ), by the way ... :)

[hu_HU.inc.txt](https://github.com/Offerel/roundcube_primitivenotes/files/4064543/hu_HU.inc.txt)

**Comment by Offerel** [comment]
Many thx for the language file. I will include it for the next release. Regarding note attaching: This is already possible at this stage. There is a Share button in the toolbar. If you click on it, the note will be attached to a new e-mail.

**Comment by abcug** [comment]
Then it was very well hidden! :) I downloaded the version 1.5.4 with composer and manually the the dev-master... checked the translate files ( all of them ), bitmps, also the source... I did not find any share button... :) I think you meant the 'send' button, which allows me to send a note as a new email. What I was thinking was an option to associate a note with a received (existing) email. If we talk about one, then I found a bug! :)))

**Comment by Offerel** [comment]
Yes, i mean the send button. But i think you mean the other way around, set a mail as note... I fear this isn't possible from my side. For my understanding, such a function must be come from the mail functions. If i remember correctly, there is no hook for a e-mail do send the mail or its content or body to a third-party addon. If you know another addon which provides such a function, please let me know.

**Comment by abcug** [comment]
No-no-no. I don't want to send or poke any mails. They are as good as they are... :) Your plugin perfect except that i would like use as a 'post-it' attached to the mail and not like a 'standalone note'. There are a plugin named 'kolab/tasklist' which do almost the same but that much like shooting a sparrow by cannon. The essence here is that i can attach additional info to the mail as a note. Also there are a plugin named 'weird-birds/thunderbird_labels' which can add colors or icons to the mail list and mail view. This way you can indicate that a note is attached to the mail.

**Comment by Offerel** [comment]
Ahh ok, I will try to look at the plugins you mentioned and tell you if something possible.

**Comment by CombeeMike** [comment]
Any update on this one? I'm also looking for a way to write arbitrary notes and attach them to a mail. In fact I'm only looking for this feature as I don't need no "standalone note taking" within roundcube at all.

**Comment by Offerel** [comment]
@CombeeMike This is a function for which this AddOn is not intended. Its primary purpose is to be some kind of simple replacement for OneNote or EverNote. And this platform independent and as compatible as possible to open standards. That is why the focus is on the Markdown format. The function you are looking for is almost worth to create a separate AddOn for it. Maybe it would be easier than to extend my AddOn accordingly.

Personally I would have no use for such a function or at least I don't see any real sense in it. But this is only my personal opinion. Maybe others see it differently. I leave it up to everyone to use my AddOns and develop something else out of them.

On the other hand, if there are more people who want such a function, maybe I would develop something like that. It should really be useful for many people and not just for a handful of users.

**Comment by CombeeMike** [comment]
Hi @Offerel , thank you very much for those open words! This way I know what I can hope (or not hope) for regarding your plugin!

**Comment by Offerel** [comment]
I have added your language file to the latest version. I will try to find a solution for your request in the next days. Since more phrases wwas added in the last 2 years, i have added them ith help of google to your language file. Hopefully my phrases are correct.
