### ISSUE TITLE
Is it possible to modify the tool to create folders?

### ISSUE THREAD

**Issue by Hariko50** [Offerel/roundcube_primitivenotes#26]
I am not a big fan of tags, I personally find nested folder structures clearer. And you don't have to remember the names of the tags.

**Comment by Offerel** [comment]
One of the features of the existing structure is the flattest possible structure of the notes. This is the only way to keep them compatible with most of the Markdown applications and apps. An additional folder structure would break this advantage. Therefore it is not planned to support such a feature. Of course you are free to fork the repository and make your own adjustments in your fork.
