### ISSUE TITLE
Error with Plugin loaded but not running

### ISSUE THREAD

**Issue by wawefr** [Offerel/roundcube_primitivenotes#34]
Hi 
very sorry, but the plugin is "uploaded" but not running
i send you the log files where you will find somes explanations
many thankscfor your help
Fred
[apache-errors.log](https://github.com/Offerel/roundcube_primitivenotes/files/5212636/apache-errors.log)
[roundcube-errors.txt](https://github.com/Offerel/roundcube_primitivenotes/files/5212631/roundcube-errors.txt)

**Comment by Offerel** [comment]
It seems something is wrong configured. Either the plugin is in the wrong path or the relative path to roundcube has a wrong path. Additionally it seems something with directory permission is set with wrong privilege's.

Please check the path for the plugin itself and the path you have specified for the variables inside the primitivenotes configuration file. 

Additionally you should check if the plugin or better your php instance has write privilege's in the directory where you try to upload your notes with the plugin and in temporary paths, where attachments are for roundcube are uploaded.

**Comment by wawefr** [comment]
Hello .I corrected the settings but I still have a problem (see file)
Thank you
[error apache.log](https://github.com/Offerel/roundcube_primitivenotes/files/5225156/error.apache.log)
[errors roundcube.log](https://github.com/Offerel/roundcube_primitivenotes/files/5225157/errors.roundcube.log)

**Comment by Offerel** [comment]
According to your apache log, apache or better your php interpreter does not have write access to save infos in the given logfilepath: /etc/roundcube/plugins/errors.log. 

In the Roundcube error logfile its the same issue. In this case you have configured /home/frederic@patat-monnot.com/notes/ to save the notes the, but the php process does not have write privileges to this directory.

So you have to check whats the user under which your php process runs and give this user or the group wo what the user belongs at least write privileges for the mentioned directories.

**Comment by wawefr** [comment]
Hello
I have always the problem off Driver of database
I change the right for "Notes" where every has all right see capture
thanks for your help
[error plugin.log](https://github.com/Offerel/roundcube_primitivenotes/files/5232080/error.plugin.log)
[errors roundcube.log](https://github.com/Offerel/roundcube_primitivenotes/files/5232081/errors.roundcube.log)
![droit notes](https://user-images.githubusercontent.com/62282235/93336148-a8f0fc80-f827-11ea-9c4c-533f96ac7b76.PNG)

**Comment by Offerel** [comment]
- You have configured a wrong or unsupported database driver in your roundcube configuration file. 
- Permissions are wrong in /etc/roundcube/plugins/errors.log
- For some reason, your php interpreter can't write to /var/vmail/patat-monnot.com/frederic@patat-monnot.com/notes/
- All these are issue's i can't really help, since there can be several system relevant problems, i can only say, whats the problem and what you have to solve. It depends on your system how you can solve this issues.
- Additionally, i wouldn't recommend to set set /var/vmail/patat-monnot.com/frederic@patat-monnot.com/notes/ to 777 because this a security risk.

**Comment by wawefr** [comment]
Thanks for your feedback
About the unsupported database driver in your roundcube configuration file, it's ok for other plugins which use DB
For the installation of my system I take this procedure https://workaround.org/ispmail/buster/
I will continue to check and if I find a solution I will explain to you

**Comment by Offerel** [comment]
Closed, since there was no reponse
