### ISSUE TITLE
can't make new notes

### ISSUE THREAD

**Issue by NachoSUANZES** [Offerel/roundcube_primitivenotes#35]
Hello, 
I install the plugin and  it appears perfectly on the web app under the Notes icon on the left menu. when I clic on Notes and try to make a new note nothing happens.
any guess?

**Comment by NachoSUANZES** [comment]
Hi, 
solved, I misspelled the user directory on config.
thank you

**Comment by Offerel** [comment]
Nice that you got it to work. If you have any questions, just get in touch.
