### ISSUE TITLE
PHP 8.0 required changs

### ISSUE THREAD

**Issue by syncgw** [Offerel/roundcube_primitivenotes#36]
notes.php:339: $yhe_pos = strpos($contents, $yh_end, ($l = strlen($yh_begin)) < strlen($content) ? $l : 0);

**Comment by Offerel** [comment]
Can you please tell me whats wrong with this in PHP8? 

Currently line 339 looks like:
`$yhe_pos = strpos($contents, $yh_end, strlen($yh_begin));`

According to the documentation, `$yh_end` must not be a int. It isn't an int, it is a string. In default configuration it should be "---". I'm a little bit clueless what you mean.

**Comment by syncgw** [comment]
`Fatal error: Uncaught ValueError: strpos(): Argument #3 ($offset) must be contained in argument #1 ($haystack) inroundcube\plugins\primitivenotes\notes.php:339 Stack trace: #0 roundcube\plugins\primitivenotes\notes.php(341): strpos('', '---', 3) #1 {main} thrown in roundcube\plugins\primitivenotes\notes.php on line 339`
If length of `$content` is e.g. `0`, then the function fails.

**Comment by Offerel** [comment]
In my opinion, this is not a PHP8 issue. If the first argument is empty, then the AddOn has a problem to read the notes file or at least the file is empty. In that case, the first argument length is zero. That's the reason why it fails.

Are there more errors in the logfile? If yes, please check the privileges of the notes directory. Additionally, you should also check, if there are notes files, which are empty.

One additional hint from my side: I'm not sure, if Roundcube itself is ready for PHP8 as of yet. To my knowledge, there was no official statement. In most of the bigger Linux distributions, PHP8 is not officially supported and mostly only experimental.

**Comment by syncgw** [comment]
Yeah I'm with you - I know RC is not officially supporting PHP 8 up to now (tons of warnings and error messages in PHP 8). 

I've some plugin created which I want make them ready for PHP8. One of them is to synchronize notes from RC using you plugin. That's why I stumbled over the fatal error.

It's not a priviledge problem. It might happen a user creates a empty file like `Sunny[cat1 cat2 cat3].md` for future use (at least we have one user making such things). So I think it would be a great idea to deal with such files without ending with a fatal error. Depending on error settings in PHP8, a message might be written to log file, but user only see no notes at all. This might result in a user calling admin where all of his/her very very important notes has gone... :-)

**Comment by Offerel** [comment]
I have tried to make a fix for this in commit [a3851a1](https://github.com/Offerel/roundcube_primitivenotes/commit/a3851a190280848f4db9f023a5eb0a406bd8c8cf). Can you please try, if that solves the issue for you?

**Comment by syncgw** [comment]
Copies file from Fix. Here you see, I got new one:
`339:$yhe_pos = strlen($contents) >= strlen($yh_begin) ? 0 : strpos($contents, $yh_end, strlen($yh_begin));
`

Still:

`[31-Dec-2020 12:58:58 Europe/Berlin] PHP Fatal error:  Uncaught ValueError: strpos(): Argument #3 ($offset) must be contained in argument #1 ($haystack) in roundcube\plugins\primitivenotes\notes.php:339
Stack trace:
#0 roundcube\plugins\primitivenotes\notes.php(339): strpos('', '---', 3)
#1 {main}
  thrown in roundcube\plugins\primitivenotes\notes.php on line 339`

Sorry, that didn't solve problem..

**Comment by Offerel** [comment]
My fault. I must have miss-configured something on nginx, i couldn't test the addon. The new fix should solve the issue. I have tested it at least against the filename you have mentioned. If that work for you, i have some additional changes for this addon, before i make a new release. If that works for you, please drop me a line, then i will add the next changes tomorrow after silvester coma and make a new release.

**Comment by syncgw** [comment]
Yeah, that's it. Solved problem. Thank you for your support. And.. happy new year!

**Comment by syncgw** [comment]
Yeah, that's it. Solved problem. Thank you for your support. And.. happy new year!
