### ISSUE TITLE
config.inc.php

### ISSUE THREAD

**Issue by syncgw** [Offerel/roundcube_primitivenotes#39]
Not really a bug, but it would make work easier during updates. You're delivering `config.inc.php` as part of the plugin. Every time a update is installed, admin needs to be aware to restore this file from backup. 

Usually plugins should try to load `config.inc.php` and if not found fall back to `config.inc.php.dist`. Seems this is also implemented in your plugin, but since you're delivering `config.inc.php`, no persistent local configuration is possible...

**Comment by Offerel** [comment]
To my knowledge `config.inc.php` is not part of the release package. If you look here at the files, this file is not there. So, if you install the release package, there should be no such file. 

And yes, I'm with you, this file should hold the personal configuration and such should not be overwritten by a new release. 

![grafik](https://user-images.githubusercontent.com/14041522/103538683-f8bb0880-4e96-11eb-91ca-4b14dd9ad1ca.png)
As you can see in the screenshot, there is no such file in the release package...

**Comment by syncgw** [comment]
I just installed a fresh and new RC and `primitivenotes` in a empty directory with composer. For whatever reason `config.inc.php` is created.

![grafik](https://user-images.githubusercontent.com/2334583/103547004-1b9fe980-4ea4-11eb-9a9c-3fbbaebe8cfd.png)

**Comment by Offerel** [comment]
I have no idea, what composer does there. I have never used composer before in my life, since I personally didn't like the way composer works. The composer.json file is only included, since this is a basic requirement for the repository.

Personally I prefer either git checkout or downloading/extracting the archiv manually.

**Comment by Offerel** [comment]
After looking at the source of composer installation, the file will be created by every installation via composer automatically. I have no idea if there is a way to use some update process where the file will not be overwritten.
