### ISSUE TITLE
Searching Keywords

### ISSUE THREAD

**Issue by sai-mike** [Offerel/roundcube_primitivenotes#4]
I was entering single keywords for notes and they did not show in search results.  I did additional testing and found the following.

If two keywords are entered separated by a space, saving the note automatically adds a comma between them and the note will show in the search results:

![kw01](https://user-images.githubusercontent.com/35618397/35476344-491e302c-0363-11e8-96eb-9f935e1d279b.jpg)

![kw02](https://user-images.githubusercontent.com/35618397/35476346-51371936-0363-11e8-8aee-61c34b9551b1.jpg)

If a single keyword is entered without a comma, one is not added automatically when saving and the note will not show in the search results:

![kw03](https://user-images.githubusercontent.com/35618397/35476359-7f9cd2fc-0363-11e8-9081-e7ce32a70992.jpg)

If a comma is manually entered after a single keyword when creating or editing the note, then it displays properly in the search results:

![kw04](https://user-images.githubusercontent.com/35618397/35476370-a57c3328-0363-11e8-8dc1-96bf884d39c0.jpg)

**Comment by Offerel** [comment]
thx for the detailed report. should be fixed in the latest commit. I didn't make a new release for this. please checkout or download master.zip
