### ISSUE TITLE
Attached media(s) doesn't get deleted when note is deleted.

### ISSUE THREAD

**Issue by DongWang111** [Offerel/roundcube_primitivenotes#42]
The attached media(s) in the note(s) for primitive_notes doesn't get deleted when the note(s) is deleted. Media(s) remains in the ".media" folder.

**Comment by Offerel** [comment]
Right, that's how it's meant to be. There is no function to delete other files. The risk of deleting files that are still needed is too high. From my point of view, however, this is of little consequence. The primary format used is Markdown and this is designed to transport text information. As a general rule, embedded media are used rather rarely. For myself, about 3% of the Markdown files use embedded media and these files share the media. So they are reused across different files. If you were to delete them automatically, these media would also be lost for the other files.

**Comment by Offerel** [comment]
I have committed a test in the dev branch with commit [f5cd5e2](https://github.com/Offerel/roundcube_primitivenotes/commit/f5cd5e210519a3cc744c78cb443b9975aede7fb3). In this i added a switch in the settings. If you set this to true/on, it try to find embedded media files in a markdownfile (and only a markdownfile) and deletes this files automatically. As stated before, i cant recommend to use such a function, as it will blindly delete all files embedded in markdown file. There will be no additional confirmation before media files will be deleted.

If this is what you want, i can make a cleaner version. There will be no variant for html files.

**Comment by Offerel** [comment]
I have removed this commit and made a new branch instead. This new branch "rm_html" removes html file support completely and adds requests in another form. The change is, that it checks if the media files to be removed are local files or remote files and additionally, it asks the user for confirmation for removing this local files after the note was successfully removed. This confirmation will appear only, if the option to remove media files is enabled. If the function is disabled, only the note itself will be removed, media files stays at their place.
