### ISSUE TITLE
$config['notes_basepath'] in docker

### ISSUE THREAD

**Issue by NadeoGolf** [Offerel/roundcube_primitivenotes#43]
Hello,

I don't understand how to configure the plugin with docker, I created a folder in /var/www/html/ which is called notes but when I want to create a notes, it marks Permission denied in the docker log

I put the path in the config.inc.php file

I don't know where to create the folder otherwise

**Comment by Offerel** [comment]
In this case, it seems that the folder can't be accessed with proper privileges from within docker. I have no idea what privileges are needed for docker, to get this working as expected. I cant help you with docker support. 

BTW: If `/var/www/html/` in your case is the Webroot folder, i would not recommend to store your notes there. This could be a security risk.

**Comment by thereisnotime** [comment]
@NadeoGolf here is a dirty solution:
1. Edit  ./www/plugins/primitivenotes/config.inc.php and change the notes_basepath to be /notes/
2. In your docker-compose directory do:
mkdir notes
chown -R www-data:www-data ./notes
3. In your docker-compose add a volume to be used only for notes
- ./notes:/notes
4. Restart your containers.

**Comment by NadeoGolf** [comment]
thanks a lot, it worked.
