### ISSUE TITLE
2.0.6 config.inc.php not loaded

### ISSUE THREAD

**Issue by syncgw** [Offerel/roundcube_primitivenotes#55]
Hi,
I just installed a new Rc 1.4.11 with 2.0.6. 
Copied config.inc.php from backup to plugin/primitivenotes and enables plugin.
It does not find existing notes...

Downgrading to 1.5.7 (and copying config.inc.php from backup) made plugin work again.

Pls check.

**Comment by Offerel** [comment]
Please have a look at the changelog. The config options for the path has been changed.

**Comment by syncgw** [comment]
What a shame - sorry for skip reading changelog...

**Comment by Offerel** [comment]
:-) No problem. I fear most people did not read changelog's or readme's
