### ISSUE TITLE
can't create none

### ISSUE THREAD

**Issue by bv217** [Offerel/roundcube_primitivenotes#6]
Hello!
I can’t create a note.
In the logs there are such records:
PHP Warning:  usort() expects parameter 1 to be array, null given in …\roundcube\plugins\primitivenotes\notes.php on line 233
PHP Warning:  Invalid argument supplied for foreach() in …\roundcube\plugins\primitivenotes\notes.php on line 519
PHP Warning:  file_get_contents(…/Notes): failed to open stream: Permission denied in …\roundcube\plugins\primitivenotes\notes.php on line 253
PHP Warning:  fopen …/Notesggg[hgh].md): failed to open stream: Permission denied in …\roundcube\plugins\primitivenotes\notes.php on line 181
PHP Warning:  fwrite() expects parameter 1 to be resource, boolean given in …\roundcube\plugins\primitivenotes\notes.php on line 182
PHP Warning:  fclose() expects parameter 1 to be resource, boolean given in …\roundcube\plugins\primitivenotes\notes.php on line 183
This is similar to a rights issue, but another plugin, storage, with the same entry $config['storage_basepath'] in config.inc.php works fine. All folders are created normally.
What could be the problem?
IIS 8

**Comment by Offerel** [comment]
I assume the directory with the notes is empty? If thats the case, you can try to put there at least 1 note. In the meantime, i try to fix this.

**Comment by bv217** [comment]
The plugin create folders of the form Notes1[1].html, Notes2[2].md, Notes3[3].txt,  but nothing more.

**Comment by Offerel** [comment]
Hmm that wasn't supposed to happen (creating tdirs by this names). I'll take a look at this.

**Comment by bv217** [comment]
Works, added a backslash at the end of the $config['notes_folder'] = '/Notes/'; 
Thanks

**Comment by Offerel** [comment]
Yes, that's corect, the path should allways end with a backslash as in the example config. Does the error above is also solved with this?

**Comment by bv217** [comment]
Yes

**Comment by Offerel** [comment]
OK. Then i will check in one of the next commits, if the path end's with a backslash and if not, il add this automatically. Il close this issue for now.

**Comment by Offerel** [comment]
in the latest commit https://github.com/Offerel/roundcube_primitivenotes/commit/f7bc320234bb0421b557dd632273eef97739a5d8, there is now a check for ending backslash. However i do not add the backslash automatically. It only throws a error message in Roundcubes error.log and stops the plugin.
