### ISSUE TITLE
Causes issue with mail Subjects; always default "Send by e-mail:"

### ISSUE THREAD

**Issue by jaredthomson** [Offerel/roundcube_primitivenotes#9]
Running Roundcube ver. 1.3.6 and plugin 1.3.0

First, I like the plugin and it will be useful after this is addressed.

 Essentially, as the subject states, all composed messages open with a default subject of "Send by e-mail:".  This is true with compose, reply, reply-all and forward.  Appears to be caused by the primitive notes plugin.

Recommendation for future versions; using an IMAP folder would be great. On the IPhone there is a default Notes folder created in mailboxes and pulling from this to edit would be infinitely useful.

Thanks,

Jared

**Comment by Offerel** [comment]
I have fixed the issue with the e-mail subject. Many thx for reporting.

Regarding your recommendation with the IMAP folder: I would not recommend using an IMAP folder for anything other than email storage. This is at least not a standard application case for IMAP and carries the risk that e-mail clients cannot handle it. In addition, this would make simple synchronization of notes almost impossible. Currently, the notes are saved as individual files in a previously defined directory. This makes it very easy to keep these notes in sync with any device without having to change the standards.

**Comment by jaredthomson** [comment]
Awesome, appreciate the quick response.

Thanks for following up about my IMAP question; understood and I do agree. 

This may not change your mind, but I did take a look at the notes more closely.  Essentially, apple devices create emails in a "Notes" IMAP folder and these have pre-set headers based on account and other ones based on the note.  Essentially, I'd like to be able to open my these emails in the primitive notes pane.

I may attempt to figure this out myself as it would be nice to have a similar interface as you have worked on; i.e. open the notes pane and have all the individual ones easily accessible on the left rather than going through the e-mail compose per note (email). The following is an example of the headers if you do have any interest.  

Anyway, thanks again!

Content-Type: text/html; charset=utf-8
Content-Transfer-Encoding: 7bit
Subject: Things to do
From: Test User <testuser@whatever.com>
X-Universally-Unique-Identifier: 2A563DD4-24E4-44F3-87BF-94722921E7C3
X-Uniform-Type-Identifier: com.apple.mail-note
Message-Id: <AEE77364-C47C-422F-9054-564541B55FF0@whatever.com>
Date: Thu, 28 Jan 2016 22:43:17 -0500
X-Mail-Created-Date: Thu, 15 Jan 2015 09:05:12 -0500
Mime-Version: 1.0 (iOS/9.2.1 \(13D15\) dataaccessd/1.0)

**Comment by Offerel** [comment]
That looks for me like a standard mail header. Only "X-Uniform-Type-Identifier" is something special from apple. Maybe it's possible to open such a marked mail in the notes plugin, instead as a e-mail. Feel free to write your own patch for this behaviour. But keep in mind that only a handful of people use apple apps and most others use other clients. So we must be sure that we don't interfere with the standard behaviour.
